2021.09: Pulling from syword/python3-pytorch
Digest: sha256:94a36185a4cdc75b9298302e3deb78f766aa9c2ac9a71ed32bef131841e538cf
Status: Image is up to date for syword/python3-pytorch:2021.09
docker.io/syword/python3-pytorch:2021.09
Traceback (most recent call last):
  File "/my-projects/Projects/PM25_Speices_DL_2023/code/Data_Processing/derive_TrainingDatasets/main.py", line 20, in <module>
    derive_TrainingDatasets(species=species,channel_names=channel_names,width=11, height=11, special_name = special_name,YEAR=YEAR)
  File "/my-projects/Projects/PM25_Speices_DL_2023/code/Data_Processing/derive_TrainingDatasets/Convert_TrainingData_pkg/Assemble_Func.py", line 24, in derive_TrainingDatasets
    lat_index, lon_index  = load_lat_lon_indices(species=species)
  File "/my-projects/Projects/PM25_Speices_DL_2023/code/Data_Processing/derive_TrainingDatasets/Convert_TrainingData_pkg/iostream.py", line 34, in load_lat_lon_indices
    lat_index = np.save(lat_index_infile)
  File "<__array_function__ internals>", line 4, in save
TypeError: _save_dispatcher() missing 1 required positional argument: 'arr'
